version: 2.1

orbs:
  lacework: lacework/lacework@1.1.1
  docker: circleci/docker@1.4.0

jobs:
  packer-build:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run: 
          name: Validate Packer Config
          command: packer validate ubuntu1804-base.json
      - run: 
          name: Build AMI and Validate with Lacework Vulnerability Scanning
          command: packer build ubuntu1804-base.json

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: sfordlacework/lacework-cli
      - docker/push:
          digest-path: /tmp/digest.txt
          image: sfordlacework/lacework-cli
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  packer-build-ami-scan:
    jobs:
      - packer-build
  docker-build-push-scan:
    jobs:
      - build-and-push
      - lacework/ctr-vuln-scan:
          requires:
            - build-and-push
          registry: index.docker.io
          repository: lacework/lacework-cli



